# Generated by Django 4.1.5 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('firstname', models.TextField()),
                ('password', models.TextField(default=0)),
                ('lastname', models.TextField()),
                ('birthdate', models.DateField()),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.TextField(default=True, null=True)),
                ('buyername', models.TextField(default=True, null=True)),
                ('gender', models.TextField(default=True, null=True)),
                ('age', models.TextField(default=True, null=True)),
                ('qualification', models.TextField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='')),
                ('baseaddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sellroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('area', models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)')),
                ('sellprice', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('lastdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacanthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('area', models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)')),
                ('rent', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('lastdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacantroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('area', models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)')),
                ('room_mate_present', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0)),
                ('room_mate_require', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0)),
                ('rent', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('lastdate', models.DateField()),
            ],
        ),
    ]
