# Generated by Django 4.1.5 on 2023-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_req_age_alter_req_buyername_alter_req_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='age',
        ),
        migrations.AddField(
            model_name='register',
            name='qualification',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=True),
        ),
    ]
