# Generated by Django 4.1.5 on 2023-04-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_req_age_register_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='address',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='req',
            name='rent',
            field=models.TextField(default=0),
        ),
    ]
