# Generated by Django 4.1.5 on 2023-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_req_address_req_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='email',
            field=models.TextField(default=0),
        ),
    ]
